config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :webs
  resources :meetings
  root 'homes#index'


  

  get "/all_meetings", to: "meetings#all_meetings"
  get "/all_schedule_meetings/:type", to: "meetings#all_schedule_meetings"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/webs/_form.html.erb
<%= form_with(model: web, local: true) do |form| %>
  <% if web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
        <% web.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :agenda %>
    <%= form.text_field :agenda %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_field :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_field :end %>
  </div>

  <div class="field">
    <%= form.label :enabledAutoRecordMeeting %>
    <select name="enabledAutoRecordMeeting" >
    <option value="1">True</option>
    <option value="2">False</option>
    </select>
  </div>

  <div class="field">
    <%= form.label :allowAnyUserToBeCoHost %>
    <select name="web[allowAnyUserToBeCoHost]" >
     <option value="1">True</option>
    <option value="2">False</option>
    </select>
  </div>
 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webs/all_schedule_meetings.html.erb
<p id="notice"><%= notice %></p>

<a href="/all_schedule_meetings/live" class="btn btn-info">Live Meetings</a>
<a href="/all_schedule_meetings/schedule" class="btn btn-info">Schedule Meetings</a>
<a href="/all_schedule_meetings/upcoming" class="btn btn-info">Upcoming Meetings</a>
<h1>All Meetings</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>host_id</th>
      <th>topic</th>
      <th>type</th>
      <th>start_time</th>
      <th>duration</th>
      <th>timezone</th>
      <th>join_url</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @webs["webs"].each do |meeting| %>
      <tr>
        <td><%= meeting["id"] %></td>
        <td><%= meeting["host_id"] %></td>
        <td><%= meeting["topic"] %></td>
        <td><%= meeting["type"] %></td>
        <td><%= meeting["start_time"] %></td>
        <td><%= meeting["duration"] %></td>
        <td><%= meeting["timezone"] %></td>
        <td><a href="<%= meeting["join_url"] %>" target=_blank>Meeting Link</a></td>
        <%#= link_to 'Show', meeting %>
      </tr>
    <% end %>
  </tbody>
</table>
<td><a href="https://webexapis.com/v1/meetings"></a></td>

<br>

<a href="https://zoom.us/oauth/authorize?response_type=code&client_id=LFkqqeVlSPuJeT1mLGVsPA&redirect_uri=http://localhost:3000/">geberate token</a>
<%= link_to 'New Meeting', new_meeting_path %>

app/views/webs/edit.html.erb
<h1>Editing Web</h1>

<%= render 'form', web: @web %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webs</h1>

<table>
  <thead>
    <tr>
      <th>HostName</th>
      <th>Meeting</th>
    </tr>
  </thead>

  <tbody>
    <% @webs.each do |web| %>
      <tr>
        <td><%= web["hostDisplayName"]%></td>
        <td><%= web["webLink"] %></td>
        <td><%= link_to 'Destroy', "/webs/#{web["id"]}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web', new_web_path %>
<a href="https://webexapis.com/v1/authorize?client_id=C5ec2f12bc1d9ba792540a19b85ca31dd28a4ae6f56de9223a51ae125a742dcc8&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000&scope=meeting%3Arecordings_read%20spark%3Aall%20meeting%3Aadmin_schedule_write%20meeting%3Aschedules_read%20meeting%3Apreferences_write%20spark-admin%3Apeople_write%20meeting%3Arecordings_write%20meeting%3Apreferences_read%20meeting%3Aadmin_recordings_read%20spark-admin%3Aorganizations_read%20spark-admin%3Aplaces_read%20spark-admin%3Aresource_group_memberships_read%20meeting%3Aschedules_write%20spark%3Akms%20spark-admin%3Adevices_read%20meeting%3Aadmin_recordings_write%20spark-admin%3Aplaces_write%20spark-admin%3Alicenses_read%20meeting%3Aadmin_schedule_read%20spark-admin%3Adevices_write%20spark-admin%3Apeople_read&state=set_state_here">geberate token</a>

app/views/webs/new.html.erb
<h1>New Web</h1>

<%= render 'form', web: @web %>

<%= link_to 'Back', webs_path %>

app/views/webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meeting:</strong>
  <%= @web.meeting %>
</p>

<%= link_to 'Edit', edit_web_path(@web) %> |
<%= link_to 'Back', webs_path %>