config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :webs
  resources :meetings
  root 'homes#index'


  

  get "/all_meetings", to: "meetings#all_meetings"
  get "/all_schedule_meetings/:type", to: "meetings#all_schedule_meetings"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	attr_accessor :start_time, :topic, :duration, :timezone, :type, :join_url, :end_date_time, :monthly_day, :monthly_week, :monthly_week_day, :meeting_type, :weekly_days, :userId

end

app/controllers/meetings_controller.rb
require 'zoomus'

class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  
def all_schedule_meetings
    require "uri"
    require "net/http"
    event_provider = EventProvider.last
    @access_token = event_provider.access_token
    @refresh_token = event_provider.refresh_token
    url = URI("https://api.zoom.us/v2/users/#{user_id}/meetings?type=#{params[:type]}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    https.read_timeout = 1
    request = Net::HTTP::Get.new(url)
    auth_header = Base64.strict_encode64(ENV["ZOOM_CLIENT_ID"]:ENV["ZOOM_SECRET"])
    request["Content-Type"] = "application/atom+xml"
    request["Authorization"] = "Bearer #{@access_token}"
    all_meetings = https.request(request)
    puts all_meetings.read_body
    @meetings = JSON.parse(all_meetings.read_body)
  end


  def index
    @meetings = Meeting.all
    if params[:code].present?
      url = URI("https://zoom.us/oauth/token?grant_type=authorization_code&code=#{params[:code]}&redirect_uri=http://localhost:3000/")
      https = Net::HTTP.new(url.host, url.port)
      https.use_ssl = true
      https.read_timeout = 1
      request = Net::HTTP::Post.new(url)
      auth_header = Base64.strict_encode64(ENV["ZOOM_CLIENT_ID"]:ENV["ZOOM_SECRET"])
      request["Content-Type"] = "application/atom+xml"
      request["Authorization"] = "Basic #{auth_header}"
      response = https.request(request)
      puts response.read_body
      response_data = JSON.parse(response.read_body)
      access_token = response_data["access_token"]
      expires_in = response_data["expires_in"]
      refresh_token = response_data["refresh_token"]
      # locale = locale
      # event_provider = Eventprovider.where(:name => "zoom").first_or_initialize
      event_provider = EventProvider.first_or_initialize
      # event_provider.provider = "zoom"
      event_provider.access_token = access_token
      event_provider.refresh_token = refresh_token
      event_provider.save
      redirect_to "/meetings/new"
    end
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  # def create
  #   @meeting = Meeting.new(meeting_params)
  #   zoomus_client.meeting_create(merge_params(meeting_params))

  #   respond_to do |format|
  #     if @meeting.save
  #       format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
  #       format.json { render :show, status: :created, location: @meeting }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @meeting.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    # begin
      # zoomus_client.meeting_create(merge_params(meeting_params))
      event_provider = EventProvider.last
      @access_token = event_provider.access_token
      @refresh_token = event_provider.refresh_token
      url = URI("https://api.zoom.us/v2/users/#{merge_params(meeting_params)["host_id"]}/meetings")
      https = Net::HTTP.new(url.host, url.port);
      https.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Content-Type"] = "application/json"
      request["Authorization"] = "Bearer #{@access_token}"
      # request.body = {"topic": params[:meeting][:topic], "type": params[:meeting][:type].to_i, "start_time": params[:meeting][:start_time], "duration": params[:meeting][:duration], "timezone": params[:meeting][:timezone],"recurrence": {"end_date_time": params[:meeting][:end_date_time], "end_times":params[:meeting][:end_times], "monthly_day": params[:meeting][:monthly_day].to_i, "monthly_week": params[:meeting][:monthly_week].to_i, "monthly_week_day": params[:meeting][:monthly_week_day].to_i, "repeat_interval": 0, "meeting_type": params[:meeting][:meeting_type].to_i, "weekly_days": params[:meeting][:weekly_days]}}.to_json

      request.body = {"topic": params[:meeting][:topic], "type": params[:meeting][:type].to_i, "start_time": params[:meeting][:start_time], "duration": params[:meeting][:duration], "timezone": params[:meeting][:timezone], "recurrence": {"end_date_time": params[:meeting][:end_date_time], "monthly_day": params[:meeting][:monthly_day].to_i, "monthly_week": params[:meeting][:monthly_week].to_i, "monthly_week_day": params[:meeting][:monthly_week_day].to_i, "repeat_interval": 0, "type": params[:meeting][:meeting_type].to_i, "weekly_days": params[:meeting][:week_days]}}.to_json
      response = https.request(request)
      
      puts response.read_body
      response_data = JSON.parse(response.read_body)
      Meeting.create(meeting: response_data["join_url"])  
       redirect_to "/meetings"
    # rescue Exception => e
    #   
    #   { error: e.message }
    # end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def zoomus_client
      @instance ||= Zoomus.new
    end

    def merge_params(params)
      params.merge({
        host_id: user_id,
        start_time: process_meeting_date(params[:start_time])
      })
    end

    def process_meeting_date(the_date)
      Time.parse(params[:meeting][:start_time]).strftime("%Y-%m-%dT%H:%M:%SZ") if params[:meeting][:start_time].present?
    end

    def user_id
      require "uri"
      require "net/http"
      event_provider = EventProvider.last
      @access_token = event_provider.access_token
      @refresh_token = event_provider.refresh_token
      url = URI("https://api.zoom.us/v2/users")
      https = Net::HTTP.new(url.host, url.port);
      https.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{@access_token}"
      response = https.request(request)
      puts response.read_body
      response = https.request(request)
      response_users = JSON.parse(response.read_body)["users"]
      account_user = []
      response_users.each do |user|
        if (user["email"] == "cuteshreya307@gmail.com")
          account_user << user
        end 
      end
      # response_user_id = account_user.last["id"]
      @user = account_user.last["id"]

      # @user ||= zoomus_client.user_getbyemail(email: "cuteshreya307@gmail.com")['id']
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:start_time, :topic, :duration, :timezone, :type, :join_url, :monthly_day, :monthly_week, :end_date_time, :monthly_week_day, :weekly_days, :end_times, :meeting_type).to_h
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>


<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time %>
  </div>


  <div class="field">
  <%= form.label :end_date_time %>
  <%= form.datetime_field :end_date_time %>
  </div>

   <div class="field">
    <%= form.label :end_times %>
    <%= form.time_field :end_times %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
  <%= form.label :duration %>
  <%= form.text_field :duration %>
  </div>


 <div class="field">
  <%= form.label :timezone %>
  <%= form.text_field :timezone %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :meeting_type %>
    <select name="meeting[meeting_type]" >
    <option value="1">Daily</option>
    <option value="2">Weekly</option>
    <option value="3">Monthly</option>
    </select>
  </div>

 <div class="field">
  <%= form.label :monthly_day %>
    <select name="meeting[monthly_day]">
    <%= (1..31).each do |daa| %>
    <option><%= daa %></option>
   <% end %>
  </select>
</div>

 <div class="field">
    <%= form.label :monthly_week %>
    <select name="meeting[monthly_week]" >
      <option value="-1">Last week of the month</option>
      <option value="1">First week of the month</option>
      <option value="2">Second week of the month</option>
      <option value="3"> Third week of the month</option>
      <option value="4"> Fourth week of the month</option>
    </select>
  </div>

<div class="field">
    <%= form.label :monthly_week_day %>
    <select data-live-search="true" data-live-search-style="startsWith" class="selectpicker" multiple="multiple" name="meeting[monthly_week_day]" >
      <option value="1">Sunday</option>
      <option value="2">Monday</option>
      <option value="3">Tuesday</option>
      <option value="4">Wednesday</option>
      <option value="5">Thursday</option>
      <option value="6">Friday</option>
      <option value="7">Saturday</option>
    </select>
  </div>

  <div class="field">
    <%= form.label :weekly_days %>
    <select data-live-search="true" data-live-search-style="startsWith" class="selectpicker" multiple="multiple" name="meeting[weekly_days]" >
      <option value="1">Sunday</option>
      <option value="2">Monday</option>
      <option value="3">Tuesday</option>
      <option value="4">Wednesday</option>
      <option value="5">Thursday</option>
      <option value="6">Friday</option>
      <option value="7">Saturday</option>
    </select>
  </div>

 



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/all_schedule_meetings.html.erb
<p id="notice"><%= notice %></p>

<a href="/all_schedule_meetings/live" class="btn btn-info">Live Meetings</a>
<a href="/all_schedule_meetings/schedule" class="btn btn-info">Schedule Meetings</a>
<a href="/all_schedule_meetings/upcoming" class="btn btn-info">Upcoming Meetings</a>
<h1>All Meetings</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>host_id</th>
      <th>topic</th>
      <th>type</th>
      <th>start_time</th>
      <th>duration</th>
      <th>timezone</th>
      <th>join_url</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @meetings["meetings"].each do |meeting| %>
      <tr>
        <td><%= meeting["id"] %></td>
        <td><%= meeting["host_id"] %></td>
        <td><%= meeting["topic"] %></td>
        <td><%= meeting["type"] %></td>
        <td><%= meeting["start_time"] %></td>
        <td><%= meeting["duration"] %></td>
        <td><%= meeting["timezone"] %></td>
        <td><a href="<%= meeting["join_url"] %>" target=_blank>Meeting Link</a></td>
        <%#= link_to 'Show', meeting %>
      </tr>
    <% end %>
  </tbody>
</table>
<td><a href="https://api.zoom.us/v2/users/#{user_id}/meetings?type=scheduled"></a></td>

<br>

<a href="https://zoom.us/oauth/authorize?response_type=code&client_id=LFkqqeVlSPuJeT1mLGVsPA&redirect_uri=http://localhost:3000/">geberate token</a>
<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Meeting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.meeting %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="https://zoom.us/oauth/authorize?response_type=code&client_id=LFkqqeVlSPuJeT1mLGVsPA&redirect_uri=http://localhost:3000/">geberate token</a>
<%= link_to 'New Meeting', new_meeting_path %>

<a href="/all_schedule_meetings/live" class="btn btn-info">Live Meetings</a>
<a href="/all_schedule_meetings/scheduled" class="btn btn-info">Schedule Meetings</a>
<a href="/all_schedule_meetings/upcoming" class="btn btn-info">Upcoming Meetings</a>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meeting:</strong>
  <%= @meeting.meeting %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>